### ISSUE TITLE
[Question] Is there any way to disable certain structures?

### ISSUE THREAD

**Issue by Nelots** [SuperMartijn642/FormationsNether#1]
If not, it would be nice to see configs for it. Specifically, I would like to be able to disable Formations Nether's ore-filled floating shards. They're incredibly easy to spot from afar, and getting 24 Ancient Debris is _absolutely nuts_ when compared to vanilla (where each chunk has less than 2 Ancient Debris on average, and they're all hidden underground). It's a balancing nightmare and is keeping me from using this mod.

**Comment by SuperMartijn642** [comment]
All structures and their spawning can be changed through a datapack just like you'd for vanilla structures. You can find the structure files for Formations Nether here: https://github.com/SuperMartijn642/FormationsNether/tree/master/src/generated/resources
To disable or change the spawning of the ore shard structures, you'd want to override the `data/formationsnether/worldgen/structure_set/ore_shards.json` file in a datapack.

> They're incredibly easy to spot from afar, and getting 24 Ancient Debris is absolutely nuts when compared to vanilla (where each chunk has less than 2 Ancient Debris on average, and they're all hidden underground).

I did not realize ancient debris was that rare. The Formations mods are still new and since I don't really play the game much, balancing them is somewhat difficult. Feel free to bring up any balancing issues and I will see if I can fix them (same for loot tables for example).
I will see if I can reduce the number of ancient debris in the ore shards (maybe replace some with nether gold ore or something) and potentially decrease how often they spawn.

**Comment by SuperMartijn642** [comment]
Ore shards can spawn with ancient debris or with gold. I have now decreased the ancient debris found in the shards to either 4 or 5 blocks. All ore shards now also contain more obsidian and can also contain lava.
I have also decreased the spawn attempts for the ore shard structures from on average once every 3 chunks to once every 4 chunks.

The changes are available in version 1.0.2.
