### ISSUE TITLE
[Bug] Warped structures in crimson biome

### ISSUE THREAD

**Issue by Dani20000** [SuperMartijn642/FormationsNether#5]
**Version Info**
- Minecraft 1.20.1
- Formations 1.0.2
- Formations Nether 1.0.5

**What mod loader are you using?**: Forge 47.3.0

**Description of the Bug**
I don't know if it's intended, but i haven't seen any structure made of crimson blocks, only warped ones (and others non-themed obviously) in either warped or crimson biomes. I tried also searching in creative with /locate. For example, i never saw a "large house" made of crimson blocks like the curseforge image gallery, only the warped one.

I suggest disable spawning these in crimson biome and/or add the same structures built of crimson blocks (if not already added and not showing because of a bug).

The "affected" structures are:
Campsite
Large House
Large Tree
Rib Cage
I don't know if there are others "themed" warped/crimson.

**Screenshots**
![2024-08-08_18 03 03](https://github.com/user-attachments/assets/2d1e38dc-2871-4352-ad58-b9534037122c)
![2024-08-08_18 05 35](https://github.com/user-attachments/assets/31de256c-2b39-443b-a737-3bc709e24a6f)

**Comment by SuperMartijn642** [comment]
Formations uses a structure processor to swap out blocks based on the biome the structure is placed in. To apply these structure processors Formations mixes into a method when the structure is placed in order to run the processors. I originally, designed and tested this is on Fabric, however it seems Forge replaces the method Formations mixes into with one that has an additional argument. As the original method wasn't being called on Forge, the structure processors weren't being applied.

I now fixed it in version 1.0.2a of Formations for Forge and NeoForge.
Thank you for reporting the issue!
